### ISSUE TITLE
nit: improve code quality based on code review

### ISSUE THREAD

**Issue by chenyuan99** [sunrisewestern/bilipod#2]
https://www.bilibili.com/video/BV1Gx4y1t7C2/?spm_id_from=333.1007.tianma.5-3-17.click&vd_source=cdc8383991bc95a3b4742f982fc72004

**Comment by sunrisewestern** [comment]
其实下载任务是并行的，天哥没有仔细看downloader.py 的实现。其他包括获取 up 主信息、视频列表、视频信息的操作很快，个人认为还是保持现在实现 减少同时请求次数防止封 ip 比较好。

**Comment by sunrisewestern** [comment]
#4 增加 docker 部署，异步部分暂时没改
