### ISSUE TITLE
FR: 筛选黑名单

### ISSUE THREAD

**Issue by ArenaDruid** [sunrisewestern/bilipod#8]
config文件可以设置keywords，但是不能设置黑名单，有的up主会发布充电视频，如果不将充电视频筛选出去，下载会出现报错。
```
2024-10-31 05:34:12.943 | ERROR    | bilipod.downloader.downloader:download_episode:45 - Failed to download BV1JaS4Y6ECZ: FFmpeg error: ffmpeg version 5.1.6-0+deb12u1 Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr --extra-version=0+deb12u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-libjxl --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared

```

**Comment by sunrisewestern** [comment]
充电视频正常是能下载的，之前有点ffmpeg参数写的有点问题，现在可以了 #9

**Comment by ArenaDruid** [comment]
> 充电视频正常是能下载的，之前有点ffmpeg参数写的有点问题，现在可以了 #9

但是我并没有充电的说（

**Comment by sunrisewestern** [comment]
没有充电会b站会给一个试听版。有个问题是现在如果下载完再充电不会再重复下载完整版，我还没想好怎么弄。
-------- Original message --------From: ArenaDruid ***@***.***> Date: 2024-10-31  11:22 a.m.  (GMT-05:00) To: sunrisewestern/bilipod ***@***.***> Cc: X Chen ***@***.***>, Comment ***@***.***> Subject: Re: [sunrisewestern/bilipod] FR: 筛选黑名单 (Issue #8) 

充电视频正常是能下载的，之前有点ffmpeg参数写的有点问题，现在可以了 #9

但是我并没有充电的说（

**Comment by ArenaDruid** [comment]
> 没有充电会b站会给一个试听版。有个问题是现在如果下载完再充电不会再重复下载完整版，我还没想好怎么弄。 -------- Original message --------From: ArenaDruid ***@***.***> Date: 2024-10-31 11:22 a.m. (GMT-05:00) To: sunrisewestern/bilipod ***@***.***> Cc: X Chen ***@***.***>, Comment ***@***.***> Subject: Re: [sunrisewestern/bilipod] FR: 筛选黑名单 (Issue #8) 充电视频正常是能下载的，之前有点ffmpeg参数写的有点问题，现在可以了 #9 但是我并没有充电的说（ —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

哦哦，行吧，那看来黑名单还是有必要的

**Comment by sunrisewestern** [comment]
@ArenaDruid 应该暂时不会添加这个功能，keyword是B站 api 原生提供的功能，没有提供blacklist
